# Generated by Django 4.1.2 on 2022-12-16 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('config_name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('model', models.CharField(choices=[('R33B', 'OX-J'), ('F31', 'SC-E'), ('F32', 'SC-F'), ('F33', 'SC-J'), ('F34', 'SC-P')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Fail',
            fields=[
                ('fail_code', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('fail_name', models.CharField(max_length=50)),
                ('process', models.CharField(choices=[('UDT', 'UpDown'), ('APS', 'APS'), ('DCR', 'DCR')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='NG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveSmallIntegerField()),
                ('fail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.fail')),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('lot_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('process', models.CharField(choices=[('UDT', 'UpDown'), ('APS', 'APS'), ('DCR', 'DCR')], max_length=3)),
                ('input', models.PositiveSmallIntegerField()),
                ('pass_qty', models.PositiveSmallIntegerField()),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.config')),
                ('ng', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.ng')),
            ],
        ),
    ]
