# Generated by Django 4.1.2 on 2022-12-16 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='ng',
        ),
        migrations.AddField(
            model_name='ng',
            name='lot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.lot'),
        ),
    ]
